---
name: Build Github Runner image for Ploigos and related tools

on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: write
jobs:
  build:
    name: Build and Push Image to Public Container Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-runner
      REGISTRY: quay.io/aagreen
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v3
      #Logic to create environment variable for tag name
      - name: Create tag name
        run: |
          branch=${{ github.ref_name }}
          tag="${branch////-}"
          echo "TAG_NAME=$tag" >> $GITHUB_ENV
      #echo '::set-output name=tag_name::$tag'
      #Build job for main branch
      - name: Build image
        if: github.ref_name == 'main'
        id: build-image-main
        uses: redhat-actions/buildah-build@v2.9
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
      #Build job for feature branches
      - name: Build image
        if: startsWith(github.ref, 'refs/heads/feature/')
        id: build-image-feature
        uses: redhat-actions/buildah-build@v2.9
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG_NAME }} ${{ github.sha }}
          containerfiles: |
            ./Containerfile
      - name: Log in to container registry
        uses: redhat-actions/podman-login@v1.3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Push to container registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}