---
name: Build Github Runner image for Ploigos and related tools
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: write
jobs:
  build:
    name: Build and Push Image to Public Container Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-runner
      REGISTRY: quay.io/aagreen
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v3
      - name: Create Tag Name
        run: |
          if  [ ${{ github.ref_name }} == main ]; then
              echo "TAG_NAME=latest" >> $GITHUB_ENV
          else
              BRANCH_NAME=${{ github.ref_name }}
              TAG="${BRANCH_NAME////-}"
              echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          fi
      - name: Build Image
        if: github.ref_name == 'main' || startsWith(github.ref, 'refs/heads/feature/')
        id: build-image
        uses: redhat-actions/buildah-build@v2.9
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG_NAME }} ${{ github.sha }}
          containerfiles: |
            ./Containerfile
      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1.3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}